### PR TITLE
Update of the FRENCH translation for E-mail on birthday extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @ForumHulp,

could you merge this, please ?

### CODE REVIEW

**Comment by karbiko** [comment]
I have tried to install this, and I got this message:
`Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\RuntimeException' with message 'The parent definition "notification.type.base" defined for definition "forumhulp.emailonbirthday.notification.type.birthday" does not exist.' in /homepages/11/d244955974/htdocs/Foro/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php:67 Stack trace: #0 /homepages/11/d244955974/htdocs/Foro/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php(50): Symfony\Component\DependencyInjection\Compiler\ResolveDefinitionTemplatesPass->resolveDefinition('forumhulp.email...', Object(Symfony\Component\DependencyInjection\DefinitionDecorator)) #1 /homepages/11/d244955974/htdocs/Foro/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Compiler/Compiler.php(105): Symfony\Component\DependencyInjection\Compiler\ResolveDefinitionTemplatesPass->process(Object(Symfony\Component\Depen in /homepages/11/d244955974/htdocs/Foro/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php on line 67`

I had installed htmlemail ext, and helper ext as well.

So, I can not explain what is happening.

Sorry if this were not the correct way to ask for support, but I hadn't found the correct place in github to do it..

Thanks in advance!

**Comment by ForumHulp** [comment]
Its the right way for asking. Did you copy the good version of notification and config files for your version?

**Comment by karbiko** [comment]
the good version...... ? ughhh?

I took the master-last one from github?
And I did the same with helper and htmlemail

And I configured my landguaje txt-file..

Anything else? 
Are there any instructions to follow? I was in forumhulp.com, but I did not understand ¿german/dutch?... and could not find extensions support there.. (I dont' recognize your landguaje in that web :d) )

where can I get them?

Thansk again!!

**Comment by karbiko** [comment]
I answer to myself!!

I found instructions in readme.md file....

I change files to use 3.1 version and now (I think) it's working!

I hope that emails congratulating birthdays will be sent tomorrow!

Is there any  scheduled time for the shipment?

Thanks!!

**Comment by ForumHulp** [comment]
Perfect,

 

It checkes twice a day

 

 

Greetz

 

 

Van: karbiko [mailto:notifications@github.com] 
Verzonden: dinsdag 21 maart 2017 22:23
Aan: ForumHulp/emailonbirthday <emailonbirthday@noreply.github.com>
CC: Forumhulp.com <info@forumhulp.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [ForumHulp/emailonbirthday] Update of the FRENCH translation for E-mail on birthday extension (#18)

 

I answer to myself!!

I found instructions in readme.md file....

I change files to use 3.1 version and now (I think) it's working!

I hope that emails congratulating birthdays will be sent tomorrow!

Is there any scheduled time for the shipment?

Thanks!!

**Comment by karbiko** [comment]
Well, message was sent, but came with some bugs

There was an error in the content, when converting the code of the message does not work a part

Here you can see an image of the message received: http://i68.tinypic.com/24uxl42.jpg

The Tag for user's name doesn't show it. It only translate it to spanish (usuario)

Numbers of years come in English, .. Where can they be switched to other languages?

And `<strong>....  and <p style...>... ` did not work either

Is there any solution?
 Thanks!

I hope you understand me with my basic level of english!!  Sorry..

**Comment by Galixte** [comment]
Hi @ForumHulp,

could you take a look, please ?

**Comment by karbiko** [comment]
Thanks Galixte..

I want to inform that there's no bug with the tag for user's name. It was my falt! (usuario was the name of the one used to test the extension...)

But the other two failures are still present,...  And they should be for other languages as well, not only for spanish translation.

**Pull request merged**
